const ASSET_BASE_URL = 'https://d1aokdoqn8tyug.cloudfront.net/LandingPageAssets/vipLandingScreen';
const COLLECTION_ASSET_BASE_URL = 'https://d1aokdoqn8tyug.cloudfront.net/LandingPageAssets/collections';

export const HOME_VIP_LAUNCH_MOBILE = `${ASSET_BASE_URL}/HOME_PAGE_MOBILE-V2.mp4`;
export const HOME_VIP_LAUNCH_TAB = `${ASSET_BASE_URL}/HOME_PAGE_DESKTOP-V2.mp4`;
export const HOME_VIP_LAUNCH_DESKTOP = `${ASSET_BASE_URL}/HOME_PAGE_DESKTOP-V2.mp4`;

export const MOTORSPORT_CARDS_DESKTOP = `${COLLECTION_ASSET_BASE_URL}/MOTORSPORT_CARDS_DESKTOP-V2.mp4`;
export const MOTORSPORT_CARDS_MOBILE = `${COLLECTION_ASSET_BASE_URL}/MOTORSPORT_CARDS_MOBILE-V2.mp4`;

export const MOTORSPORT_MOMENTS_DESKTOP = `${COLLECTION_ASSET_BASE_URL}/MOTORSPORT_MOMENTS_DESKTOP-V3.mp4`;
export const MOTORSPORT_MOMENTS_MOBILE = `${COLLECTION_ASSET_BASE_URL}/MOTORSPORT_MOMENTS_MOBILE-V3.mp4`;

export const NIGEL_MANSELL_COLLECTION_DESKTOP = `${COLLECTION_ASSET_BASE_URL}/NIGEL_MANSELL_COLLECTION_DESKTOP-V2.mp4`;
export const NIGEL_MANSELL_COLLECTION_MOBILE = `${COLLECTION_ASSET_BASE_URL}/NIGEL_MANSELL_COLLECTION_MOBILE-V2.mp4`;
